osx_image: xcode9.2
language: objective-c
xcode_project: BlockTrackerSample
xcode_scheme: BlockTrackerKit
xcode_sdk: iphoneos11.2
env:
  global:
  - FRAMEWORK_NAME=BlockTrackerKit
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script: xcodebuild -project BlockTrackerSample/BlockTrackerSample.xcodeproj -scheme
  BlockTrackerKit -configuration Release
deploy:
  provider: releases
  api_key:
    secure: zVxZe97VyxaZ3XyFgjG/9feAlhqJuheryGYuEUUkToZbt2ygUhItjmi4pVBWkwIK/iueUb8hDusJyv7knb4fzIDXw6w2b0aGqo1/9D4JBPiY2IB/94mCWs1aGdNpfDcQtHo9Powd7Izfb6NNCrE7CdIsExhNoHI5JQ5n7cWqTOggV02ibWYW9DNfgeEHYy0mCQyyHFhkEEcP5a7zZqTEcWJijLdJa1ytgWE1Nma3IyAO5hgs2kvP1ZKCxwehf767fN/+wxzQfQFupZo2KksM0cfGQVbvgkpTdzCk1Mm07vWFIxakwmPgZXv6S0OoU+gVZw2zaZobDDa8gt55u4BxtrEwFI0fWOgsff7Vg4a1B1xBEN8rW21bvnTLFmhsicI3dyif/6RXuMTIpp3tNr8YFaNt9D9OdgLZicjip0FnPFVPo+OVb1wJixaw79Wy43V5Lt79lD4Sfh75bM2fKQVVBTp3gD/Tg6O1amU6qRwp2Ld9JwPcYUsymiP7U+7qrpOXx0rymsB+eqkmPAUR4V1+Bv5fDpG3lEbgiJzYhxS4LnZ0weU5rHnOy+AODHxWFCzYvfK1Mx6WjYZN3aRt3JlRiHZYnyxFcEA6l41gl8h3WHNF9U7J1FZwtRyTUGeIn3aGVIg1VWSXaw/8M/jERiiTDYf5SQj3HIVEV4Ejt+6RStk=
  file: BlockTracker.framework.zip
  skip_cleanup: true
  on:
    repo: yulingtianxia/BlockTracker
    tags: true
